services:
  erp-web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: erp-web
    restart: unless-stopped
    environment:
      - API_URL=http://erp-backend:3001
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.erp-web.rule=Host(`erp.sanchezrepuestos.com.ar`)'
      - 'traefik.http.routers.erp-web.entrypoints=web'
      - 'traefik.http.routers.erp-web.priority=1'
      - 'traefik.http.services.erp-web.loadbalancer.server.port=3000'
    networks:
      - sanchez_docker_network

  erp-backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: erp-backend
    restart: unless-stopped
    env_file: ./apps/backend/.env.production
    volumes:
      - ./uploads:/app/uploads
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.erp-backend.rule=Host(`erp.sanchezrepuestos.com.ar`) && (PathPrefix(`/api`) || PathPrefix(`/health`))'
      - 'traefik.http.routers.erp-backend.entrypoints=web'
      - 'traefik.http.routers.erp-backend.priority=10'
      - 'traefik.http.services.erp-backend.loadbalancer.server.port=3001'
    networks:
      - sanchez_docker_network

networks:
  sanchez_docker_network:
    external: true
