services:
  erp-web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: erp-web
    restart: unless-stopped
    environment:
      - API_URL=http://erp-backend:3001
    networks:
      - sanchez_docker_network

  erp-backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: erp-backend
    restart: unless-stopped
    env_file: ./apps/backend/.env.production
    volumes:
      - erp-uploads:/app/uploads
    networks:
      - sanchez_docker_network

volumes:
  erp-uploads:

networks:
  sanchez_docker_network:
    external: true
